version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=vidyarth_vidyarthi
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_USER=vidyarth_admin
      - MYSQL_PASSWORD=&=@*b~rbJm%A
    ports:
      - '3306:3306'
