version: '3.8'
services:
  # nest-api:
  #   container_name: nest-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env

  vidyarthi-postgres:
    image: postgres:13
    container_name: vidyarthi-postgres
    restart: always
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db-vidyarthi-bkp
