export enum PermissionSubject {
  'Permission' = 'permission', 
  'Subject' = 'subject', 
  'RolePermission' = 'rolepermission', 
  'Role' = 'role', 
  'User' = 'user', 
  'CoursesOnStudents' = 'coursesonstudents', 
  'Progress' = 'progress', 
  'Achievement' = 'achievement', 
  'StudentProfile' = 'studentprofile', 
  'TeacherProfile' = 'teacherprofile', 
  'SocialProfile' = 'socialprofile', 
  'Transaction' = 'transaction', 
  'Rating' = 'rating', 
  'Course' = 'course', 
  'Category' = 'category', 
  'Duration' = 'duration', 
  'Section' = 'section', 
  'Lecture' = 'lecture', 
  'Note' = 'note', 
  'Order' = 'order', 
  'Wishlist' = 'wishlist', 
  'Cart' = 'cart', 
}