export enum PermissionSubject {
  'Permission' = 'permission', 
  'Subject' = 'subject', 
  'RolePermission' = 'rolepermission', 
  'Role' = 'role', 
  'User' = 'user', 
  'StudentProfile' = 'studentprofile', 
  'Occupation' = 'occupation', 
  'TeacherProfile' = 'teacherprofile', 
  'TeacherNotification' = 'teachernotification', 
  'SocialProfile' = 'socialprofile', 
  'Transaction' = 'transaction', 
  'Rating' = 'rating', 
  'Course' = 'course', 
  'Category' = 'category', 
  'Duration' = 'duration', 
  'Section' = 'section', 
  'Lecture' = 'lecture', 
  'Note' = 'note', 
}